services:
  - type: web
    name: ddyautokey-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
      - key: DB_HOST
        value: s1.ho.ua
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: ddyautokey1
      - key: DB_USER
        value: ddyautokey1
      - key: DB_PASSWORD
        value: ddyautokey1
